function orderFood() {
  return new Promise((resolve, reject) => {
    console.log("Order placed...");

    setTimeout(() => {
      let success = true;

      if (success) {
        resolve("Pizza delivered 🍕 ");
      } else {
        reject("Delivery failed ❌");
      }
    }, 2000);
  });
}

orderFood()
  .then(result => {
    console.log(result);
  })
  .catch(error => {
    console.log(error);
  });








//code is generated by gpt
